### 反向传播

In [36]:
import torch

# 使用标量来创建torch，并且需要保存梯度
x = torch.arange(4.0, requires_grad=True)

x, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), None)

In [37]:
# 构建 y = 2*x^2，这里是wise-element，元素对应相乘

print(x, x.grad)
y = 3 * torch.dot(x, x)
y, x.grad

tensor([0., 1., 2., 3.], requires_grad=True) None


(tensor(42., grad_fn=<MulBackward0>), None)

In [38]:
# 现在对y进行反向传播，计算y对x的导数
print(x.grad)
y.backward()
x.grad

None


tensor([ 0.,  6., 12., 18.])

In [40]:
# 验证反向传播是否正确
x.grad == 6 * x

tensor([True, True, True, True])

In [22]:
# 
x.grad.zero_()
print("x.grad:", x.grad)
y = x.sum()
print("y: ", y)
y.backward()
print("y: ", y)
print("x.grad:", x.grad)

x.grad: tensor([0., 0., 0., 0.])
y:  tensor(6., grad_fn=<SumBackward0>)
y:  tensor(6., grad_fn=<SumBackward0>)
x.grad: tensor([1., 1., 1., 1.])


#### 非标量的反向传播

不是常用的，一般都是对标量进行自动求导

In [26]:
x.grad.zero_()

y = x * x
print("y: ", y)
y.sum().backward()
x.grad

y:  tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)


tensor([0., 2., 4., 6.])