## fundamentals

In [2]:
import torch
torch.__version__

'2.0.0'

### scalar（标量）
single number，it's zero dimension tensor

In [ ]:
scalar = torch.tensor(7)
scalar

In [5]:
scalar.ndim

0

get the number from the tensor

In [6]:
scalar.item()

7

### vector（向量）

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# 向量的维度等于根据方括号的个数

vector.ndim

1

In [9]:
# 向量的元素个数是多少

vector.shape

torch.Size([2])

### matrix（矩阵）

In [10]:
matrix = torch.tensor([[7, 8], [9, 8]])
matrix

tensor([[7, 8],
        [9, 8]])

In [11]:
# 矩阵的维度是多少

matrix.ndim

2

In [12]:
# 矩阵的形状是多少

matrix.shape

torch.Size([2, 2])

### tensor（张量）

In [15]:
# 包含多个shape相同的矩阵

tensori = torch.tensor([[[7, 8, 9], [6, 7, 8], [5, 6, 7]], [[1, 2, 3], [3, 4, 5], [5, 6, 7]]])
tensori

tensor([[[7, 8, 9],
         [6, 7, 8],
         [5, 6, 7]],

        [[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [16]:
tensori.ndim

3

In [17]:
# 这个可以表示两种3*3的数据表
# 比如苹果[7, 8, 9]、香蕉[6, 7, 8]、菠萝[5, 6, 7]三天的销售额，以及铅笔[1, 2, 3]、橡皮[3, 4, 5]、作业本[5, 6, 7]三天的销量

tensori.shape

torch.Size([2, 3, 3])

In [21]:
# 文具的三天销量， 水果的三天销量
tensori[1], tensori[0]

(tensor([[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]),
 tensor([[7, 8, 9],
         [6, 7, 8],
         [5, 6, 7]]))

### random tensor （随机张量创建）

使用pytorch构建机器学习或者深度学习时，几乎不可能手动创建，所以使用随机张量构造

In [28]:
random_tensor = torch.rand(size = (3, 4))
random_tensor, random_tensor.dtype, random_tensor.type, random_tensor.shape

(tensor([[0.5642, 0.6071, 0.9450, 0.9943],
         [0.5551, 0.5731, 0.4949, 0.8299],
         [0.5193, 0.8181, 0.4359, 0.3122]]),
 torch.float32,
 <function Tensor.type>,
 torch.Size([3, 4]))

In [30]:
random_image_tensor = torch.rand(size = (224, 224, 3))
random_image_tensor.shape, random_image_tensor.dtype

(torch.Size([224, 224, 3]), torch.float32)

### zeros and ones （填充 0和1 创建）

In [34]:
zero_tensor = torch.zeros(size = (3, 4))
one_tensor = torch.ones(size = (4, 5))
zero_tensor, zero_tensor.dtype, one_tensor, one_tensor.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32,
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 torch.float32)

### range （范围创建）

使用arange创建一个范围类的tensor

In [35]:
zero_ten = torch.arange(0, 10, 0.1)
zero_ten, zero_ten.shape, zero_ten.dtype

(tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
         0.9000, 1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000,
         1.8000, 1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000,
         2.7000, 2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000,
         3.6000, 3.7000, 3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000,
         4.5000, 4.6000, 4.7000, 4.8000, 4.9000, 5.0000, 5.1000, 5.2000, 5.3000,
         5.4000, 5.5000, 5.6000, 5.7000, 5.8000, 5.9000, 6.0000, 6.1000, 6.2000,
         6.3000, 6.4000, 6.5000, 6.6000, 6.7000, 6.8000, 6.9000, 7.0000, 7.1000,
         7.2000, 7.3000, 7.4000, 7.5000, 7.6000, 7.7000, 7.8000, 7.9000, 8.0000,
         8.1000, 8.2000, 8.3000, 8.4000, 8.5000, 8.6000, 8.7000, 8.8000, 8.9000,
         9.0000, 9.1000, 9.2000, 9.3000, 9.4000, 9.5000, 9.6000, 9.7000, 9.8000,
         9.9000]),
 torch.Size([100]),
 torch.float32)

### like （利用之前的tensor创建）

In [37]:
zero_like_zt = torch.zeros_like(input=zero_ten)
one_like_zt = torch.ones_like(input=zero_ten)
zero_like_zt, zero_like_zt.shape, one_like_zt, one_like_zt.shape

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.]),
 torch.Size([100]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 torch.Size([100]))

### datatypes （利用dtype参数来构建特定数据类型的tensor）

In [ ]:
float_32_tensor = torch.tensor([7.0, 7.0, 7.0], 
                                  dtype = None,
                                  device = None,
                                  requires_grad = False)
float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 10.0],
                                  dtype = torch.float16)
float_16_tensor, float_16_tensor.dtype

### basic operation （tensor的基本运算，按照元素进行操作）

In [43]:
# 创建一个tensor，创建方式：手动（标量、向量、矩阵、张量），随机tensor，zeros and ones，范围tensor，已有复制tensor，自定义tensor

ts = torch.tensor([1, 2, 3])
ts + 10, ts * 10, ts - 1, ts / 2, ts

(tensor([11, 12, 13]),
 tensor([10, 20, 30]),
 tensor([0, 1, 2]),
 tensor([0.5000, 1.0000, 1.5000]),
 tensor([1, 2, 3]))

In [44]:
# 使用函数来进行tensor运算
torch.multiply(ts, 10), torch.add(ts, 10), torch.sub(ts, 10), torch.divide(ts, 10), ts

(tensor([10, 20, 30]),
 tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([0.1000, 0.2000, 0.3000]),
 tensor([1, 2, 3]))

In [73]:
# 向量对向量运算
# 必须要以相同的shape

ts_another = torch.ones(3, dtype = int)

ts, ts_another,ts * ts, ts.shape, ts_another.shape, torch.add(ts, ts_another)

(tensor([1, 2, 3]),
 tensor([1, 1, 1]),
 tensor([1, 4, 9]),
 torch.Size([3]),
 torch.Size([3]),
 tensor([2, 3, 4]))

In [76]:
# 矩阵对矩阵，
# 这个不是矩阵的乘法，而是矩阵的每个对应元素进行四则运算
# 所以需要相同的shape


M1 = torch.ones(size = (3, 4), dtype = int)
M2 = torch.rand(size = (3, 4))
M1, M2, M1 * M2

(tensor([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]),
 tensor([[0.4792, 0.6702, 0.3059, 0.8388],
         [0.5635, 0.8690, 0.6924, 0.1969],
         [0.8344, 0.4897, 0.3890, 0.0374]]),
 tensor([[0.4792, 0.6702, 0.3059, 0.8388],
         [0.5635, 0.8690, 0.6924, 0.1969],
         [0.8344, 0.4897, 0.3890, 0.0374]]))

### 矩阵乘法，（线性代数的矩阵乘法）

In [80]:
ts * ts, torch.matmul(ts, ts), ts @ ts

(tensor([1, 4, 9]), tensor(14), tensor(14))

In [84]:
A = torch.rand(size = (3, 2), dtype = torch.float32)
B = torch.rand(size = (2, 3), dtype = torch.float32)
C = torch.matmul(A, B)
C, C.shape, C.ndim

(tensor([[0.8917, 0.8420, 1.0560],
         [0.6886, 0.8086, 0.9007],
         [0.6849, 0.3667, 0.6603]]),
 torch.Size([3, 3]),
 2)

In [87]:
# 线性回归 y = x·A + b

torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2,
                         out_features=6)
x = A
output = linear(x)
x.shape, x, output.shape, output

(torch.Size([3, 2]),
 tensor([[0.8743, 0.7444],
         [0.8991, 0.4762],
         [0.2758, 0.7460]]),
 torch.Size([3, 6]),
 tensor([[ 1.4320,  0.4344,  0.3117, -0.0917,  0.7040,  0.7404],
         [ 1.2880,  0.2561,  0.2696, -0.2116,  0.8585,  0.7201],
         [ 1.1093,  0.5346,  0.4047,  0.1150,  0.3300,  0.3727]],
        grad_fn=<AddmmBackward0>))

### 查找

1. 查找元素
2. 查找下标

In [106]:
# 查找tensor中的常用值, min、 max、 mean、 sum
# mean和sum

x = torch.arange(0, 100, 10)
print("使用tensor的函数：", x, x.shape, x.min(), x.max(), x.type(torch.float32).mean(), x.sum())
print("使用torch的函数：", x, torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x))

使用tensor的函数： tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) torch.Size([10]) tensor(0) tensor(90) tensor(45.) tensor(450)
使用torch的函数： tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) tensor(0) tensor(90) tensor(45.) tensor(450)


In [112]:
# 查找最值min、max的下标是多少

print(x)
print("min和max的下标", x.argmin(), x.argmax())
print("")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
min和max的下标 tensor(0) tensor(9)



### 修改tensor

1. tensor的类型
2. tensor的形状

In [114]:
# 修改tensor的类型
print(x)
print("修改之前x的dtype是：", x.dtype)
print("修改之后x的dtype是：", x.type(torch.float16).dtype)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
修改之前x的dtype是： torch.int64
修改之后x的dtype是： torch.float16


In [165]:
# 修改tensor的形状

x = torch.arange(1, 9, 1)
print(x, x.shape)

y = x.reshape(2, 4)
print(y, y.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8]) torch.Size([8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) torch.Size([2, 4])


In [166]:
# 使用view来创建，当x的值是被共享的，也就是相当于多了一个引用

z = x.view(2, 4)

print(z)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [201]:
# 比较view 和 reshape
# view是数据共享的，reshape是不确定有可能是数据共享，也用可能是创建一个新的空间

x.fill_(0)

print("y: ", y)
print("z: ", z)

# 执行了32次的结果都是一致的
# 如果修改了view的值，那么x的值也随着改动，reshape同样是不确定的
z[:] = 5
print("z: ", z)
print("x: ", x)

y[:] = 4
print("y: ", y)
print("x: ", x)

y:  tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
z:  tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
z:  tensor([[5, 5, 5, 5],
        [5, 5, 5, 5]])
x:  tensor([5, 5, 5, 5, 5, 5, 5, 5])
y:  tensor([[4, 4, 4, 4],
        [4, 4, 4, 4]])
x:  tensor([4, 4, 4, 4, 4, 4, 4, 4])


In [217]:
# stacking x

x = torch.arange(1, 9, 1)
x_statcked0 = torch.stack([(x+1), (x/2).type(torch.int32), x*x, x-x], dim=0)
x_statcked1 = torch.stack([x, x, x, x], dim=1)
print(x_statcked0)
print(x_statcked1)

tensor([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [ 0,  1,  1,  2,  2,  3,  3,  4],
        [ 1,  4,  9, 16, 25, 36, 49, 64],
        [ 0,  0,  0,  0,  0,  0,  0,  0]])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8]])


In [ ]:
# 减去tensor的维度

x = torch