# torch基础

1. tensor的分类
2. tensor的创建
3. tensor的操作

In [1]:
import torch
torch.__version__

'1.13.1'

## 1. tensor的分类

### 标量、向量、矩阵、张量

0维tensor、1维tensor、2维tensor、3维tensor

In [55]:
scalar_ = torch.tensor(7)
vector_ = torch.tensor([1,2])
matrix_ = torch.tensor([[1,2],[3,4]])
tensor_ = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print("scalar_: 维度为" + str(scalar_.ndim) + "，形状为" + str(scalar_.shape) + "，值为 \n" + str(scalar_))
print("\nvector_: 维度为" + str(vector_.ndim) + "，形状为" + str(vector_.shape) + "，值为 \n" + str(vector_))
print("\nmatrix_: 维度为" + str(matrix_.ndim) + "，形状为" + str(matrix_.shape) + "，值为 \n" + str(matrix_))
print("\ntensor_: 维度为" + str(tensor_.ndim) + "，形状为" + str(tensor_.shape) + "，值为 \n" + str(tensor_))

scalar_: 维度为0，形状为torch.Size([])，值为 
tensor(7)

vector_: 维度为1，形状为torch.Size([2])，值为 
tensor([1, 2])

matrix_: 维度为2，形状为torch.Size([2, 2])，值为 
tensor([[1, 2],
        [3, 4]])

tensor_: 维度为3，形状为torch.Size([2, 3, 3])，值为 
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


## 2. 创建tensor

写死、随机、填充0或1、根据范围、根据已有的tensor

### 随机创建tensor
使用torch中的函数来创建**由随机数组成的**tensor、而不是像上面一样，手动指定

In [82]:
rand_scalar = torch.rand(size=(1,))
rand_vector = torch.rand(size=(2,))
rand_matrix = torch.rand(size=(2,2))
rand_tensor = torch.rand(size=(1,3,3))
print(rand_scalar.item())
print("\n")
print(rand_vector)
print("\n")
print(rand_matrix)
print("\n")
print(rand_tensor)

0.661022961139679


tensor([0.2221, 0.7893])


tensor([[0.2420, 0.9047],
        [0.1931, 0.3477]])


tensor([[[0.5290, 0.9812, 0.3706],
         [0.1914, 0.5206, 0.4422],
         [0.8292, 0.9566, 0.2125]]])


### 创建全0和全1的tensor

In [87]:
zero_vector = torch.zeros(size=(2,))
one_vector = torch.ones(size=(3,))
zero_matrix = torch.zeros(size=(2,3))
one_matrix = torch.ones(size=(3,2))
zero_tensor = torch.zeros(size=(1,3,3))
one_tensor = torch.ones(size=(1,3,3))
zero_vector, one_vector, zero_matrix, one_matrix, zero_tensor, one_tensor

(tensor([0., 0.]),
 tensor([1., 1., 1.]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]))

### 根据范围来创建

如果不加操作的话，那么创建的就是一个向量而已，但是，可以通过reshape、view、squeeze、unsqueeze来修改tensor的shape

In [107]:
vector = torch.arange(0, 16, 1)
re_vector = vector.reshape(4,4)
view_vector = vector.view(2,8)

### 根据已有的tensor创建相同shape的tensor

In [115]:
vector_zl = torch.zeros_like(input=rand_vector)
vector_ol = torch.ones_like(input=rand_vector)
matrix_zl = torch.zeros_like(input=rand_matrix)
matrix_ol = torch.ones_like(input=rand_matrix)
tensor_zl = torch.zeros_like(input=rand_tensor)
tensor_ol = torch.ones_like(input=rand_tensor)
vector_zl, vector_ol, matrix_zl, matrix_ol, tensor_zl, tensor_ol

(tensor([0., 0.]),
 tensor([1., 1.]),
 tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]),
 tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]))

### 指定属性创建
数据类型dtype、使用的设备device、是否需要记录梯度require_grad

In [122]:
### 默认float32、cpu、False

float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                              dtype = torch.float16,
                              device = None,
                              requires_grad = False)

float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(tensor([1., 2., 3.], dtype=torch.float16),
 torch.Size([3]),
 torch.float16,
 device(type='cpu'))

## 2. 操作tensor

1. 对应元素四则运算
2. 矩阵乘法

比如最简单的线性回归就会 y = W*x + b, W

In [165]:
vector = torch.tensor([1,2])
print(vector + 10)
print(vector - 10)
print(vector / 10)
print(vector * 10)
print(vector * vector)

matrix = torch.tensor([[1,2],[3,4]])
print(matrix + 10)

tensor = torch.rand(size=(2,3,3))
print(tensor + 10)

# 可以用scalar替代常量
scalar = torch.tensor(2)
print(vector * scalar)

tensor([11, 12])
tensor([-9, -8])
tensor([0.1000, 0.2000])
tensor([10, 20])
tensor([1, 4])
tensor([[11, 12],
        [13, 14]])
tensor([[[10.0007, 10.5687, 10.7552],
         [10.9824, 10.3315, 10.1534],
         [10.1164, 10.5870, 10.7512]],

        [[10.1718, 10.5199, 10.4790],
         [10.7279, 10.8450, 10.4779],
         [10.3379, 10.6586, 10.9703]]])
tensor([[[6.9177e-04, 5.6868e-01, 7.5520e-01],
         [9.8240e-01, 3.3149e-01, 1.5342e-01],
         [1.1643e-01, 5.8698e-01, 7.5120e-01]],

        [[1.7183e-01, 5.1995e-01, 4.7896e-01],
         [7.2787e-01, 8.4500e-01, 4.7789e-01],
         [3.3789e-01, 6.5865e-01, 9.7033e-01]]])
tensor([2, 4])


In [183]:
# 矩阵相乘
print("vector: " + str(vector) + "\n" + "matrix: " + str(matrix) + "\n" + "tensor: " + str(tensor))

## 向量相乘，（放在前面就是行向量，放在后面就是列向量）
print("vector @ vector: " + str(torch.matmul(vector, vector)))
for i in range(matrix.ndim):
    print("matrix[i] @ matrix[i]："+ str(torch.matmul(matrix[i], matrix[i])))
    
## 矩阵相乘，（tensor.shape[0], 可以得到此tensor中有几个矩阵）
print("matrix @ matrix: " + str(torch.matmul(matrix, matrix)))
for i in range(tensor.shape[0]):
    print("tensor[i] @ tensor[i]："+ str(torch.matmul(tensor[i], tensor[i])))
    print("")

## 矩阵与向量相乘，（主要是为了验证是否既可以是列向量也可以是行向量，结果是可以的，也如上所述）
print("matrix @ vector：" + str(torch.matmul(vector, matrix)))
print("vector @ matrix：" + str(torch.matmul(matrix, vector)))

vector: tensor([1, 2])
matrix: tensor([[1, 2],
        [3, 4]])
tensor: tensor([[[6.9177e-04, 5.6868e-01, 7.5520e-01],
         [9.8240e-01, 3.3149e-01, 1.5342e-01],
         [1.1643e-01, 5.8698e-01, 7.5120e-01]],

        [[1.7183e-01, 5.1995e-01, 4.7896e-01],
         [7.2787e-01, 8.4500e-01, 4.7789e-01],
         [3.3789e-01, 6.5865e-01, 9.7033e-01]]])
vector @ vector: tensor(5)
matrix[i] @ matrix[i]：tensor(5)
matrix[i] @ matrix[i]：tensor(25)
matrix @ matrix: tensor([[ 7, 10],
        [15, 22]])
tensor[i] @ tensor[i]：tensor([[0.6466, 0.6322, 0.6551],
        [0.3442, 0.7586, 0.9080],
        [0.6642, 0.7017, 0.7423]])

tensor[i] @ tensor[i]：tensor([[0.5698, 0.8442, 0.7955],
        [0.9016, 1.4072, 1.2161],
        [0.8653, 1.3714, 1.4181]])

matrix @ vector：tensor([ 7, 10])
vector @ matrix：tensor([ 5, 11])


## 3. 对tensor进行聚合


最小值、最大值、平均值、求和，（数据库的对此类操作也是用的aggregation）
此外，还可以找到最大值和最小值的下标

In [216]:
print("最小值：" + str(vector.min())  + ", " + str(torch.min(vector)))
print("最大值：" + str(vector.max())  + ", " + str(torch.max(vector)))
# print("平均值：" + str(aggregation.mean())  + ", " + str(torch.mean(aggregation)))， ***这个需要将整数的vector转成浮点数***
print("平均值：" + str(vector.type(torch.float32).mean())  + ", " + str(torch.mean(vector.type(torch.float32))))
print("求和：" + str(vector.sum()) + ", " + str(torch.sum(vector)))

print(str(matrix.min())+","+ str(matrix.max()) +","+ str(matrix.type(torch.float32).mean()) +","+ str(matrix.sum()))

a = torch.tensor([[[1,2,3], [1,2,3], [1,2,3]]])
      
tensor.min(), tensor.max(), tensor.type(torch.float32).mean(), tensor.sum()

最小值：tensor(1), tensor(1)
最大值：tensor(2), tensor(2)
平均值：tensor(1.5000), tensor(1.5000)
求和：tensor(3), tensor(3)
tensor(1),tensor(4),tensor(2.5000),tensor(10)


(tensor(0.0007), tensor(0.9824), tensor(0.5242), tensor(9.4349))

In [230]:
# 

vector_display = vector, vector.argmin().item(), vector.argmax().item()

matrix_display = matrix, matrix.argmin().item(), matrix.argmax().item()

tensor_display = tensor, tensor.argmin().item(), tensor.argmax().item()

print("vector的最小值和最大值下标：" + str(vector_display))
print("matrix的最小值和最大值下标：" + str(matrix_display))
print("tensor的最小值和最大值下标：" + str(tensor_display))

vector的最小值和最大值下标：(tensor([1, 2]), 0, 1)
matrix的最小值和最大值下标：(tensor([[1, 2],
        [3, 4]]), 0, 3)
tensor的最小值和最大值下标：(tensor([[[6.9177e-04, 5.6868e-01, 7.5520e-01],
         [9.8240e-01, 3.3149e-01, 1.5342e-01],
         [1.1643e-01, 5.8698e-01, 7.5120e-01]],

        [[1.7183e-01, 5.1995e-01, 4.7896e-01],
         [7.2787e-01, 8.4500e-01, 4.7789e-01],
         [3.3789e-01, 6.5865e-01, 9.7033e-01]]]), 0, 3)


## 修改tensor

1. 修改tensor的数据类型
2. 修改tensor的形状（reshape、view、squeeze、unsqueeze）

In [245]:
# 修改tensor的数据类型， 
vector.type(torch.float32)

tensor([1., 2.])

In [254]:
# 修改固定的向量为矩阵、张量，也就是修改tensor的形状
a_v = torch.arange(0,16,1)
a_m = a_v.reshape(4, 4)
a_t = a_m.reshape(2,2,4)
a_m = a_t.reshape(2, 8)

## 除了reshape，还有view
a_m = a_v.view(8, 2)
a_t = a_v.view(4, 2, 2)

## 这两者的区别是，reshape有可能会进行深拷贝，而不是想view是会进行浅拷贝
## 可以通过对数据进行修改，来验证

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]])

In [ ]:
# 复制tensor